### PR TITLE
Added support for TFLint with --deep parameter

### PR DESCRIPTION
**Pull request by costingalan**
Added support for TFLint (https://github.com/wata727/tflint).

This commit addresses #37 

Signed-off-by: Costin Galan <costin.galan@mambu.com>

### CODE REVIEW

**Comment by xakraz** [comment]
Please @antonbabenko merge this one 😇

**Comment by antonbabenko** [comment]
Thanks @costingalan and the rest for this addition!

[v1.19.0](https://github.com/antonbabenko/pre-commit-terraform/releases/v1.19.0) has been released.

PS: I apologize for the delay, but summer break is over now.

**Comment by luizm** [comment]
Hi there.


The --deep parameters only supported by aws provider, so I run `tflint --deep` against another kind of resource, like google I will receive an error.

```
Error: Failed to initialize a runner: No valid credential sources found
```

How are you handling it?

**Comment by Vlaaaaaaad** [comment]
Is there a specific reason this was merged with `--deep` included? Lots of people don't have AWS credentials for say production environments and `tflint --deep` will fail while `tflint` would work and still be very helpful.

Would say 2 hooks make more sense instead:
- terraform_tflint
- terraform_tflint_deep

I might be able to submit a PR for this.

**Comment by benmontour-wf** [comment]
I'd also like to see --deep maybe moved to an arg instead of included by default

**Comment by antonbabenko** [comment]
[v1.21.0](https://github.com/antonbabenko/pre-commit-terraform/releases/v1.21.0) of this module has been just released.

It is now possible to specify it like this:
```
    - id: terraform_tflint
      args: ['--deep']
```

**Pull request merged**
