### PR TITLE
fix: Support custom TF paths which contains spaces

### LINKED ISSUE #713: Terraform hook fails when the terraform binary's path contains a space
### Describe the bug

Terraform hook fails when the terraform binary's path contains a space.

### How can we reproduce it?

```bash  
ln -sf $(which terraform) path/to/terraform
ln -sf $(which terraform) path/w\ ith/space/terraform
${PWD}/path/to/terraform -v
${PWD}/path/w\ ith/space/terraform -v
export PCT_TFPATH="${PWD}/path/to/terraform"; pre-commit run --all
export PCT_TFPATH="${PWD}/path/w ith/space/terraform"; pre-commit run --all
```  

Do you have long logs to share? Please use collapsible sections, that can be created via:

<details><summary>LOGS</summary>

```bash
$ ${PWD}/path/to/terraform -v
Terraform v1.9.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/null v3.2.2
```
```bash
$ ${PWD}/path/w\ ith/space/terraform -v
Terraform v1.9.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/null v3.2.2
```
```bash
$ export PCT_TFPATH="${PWD}/path/to/terraform"; pre-commit run --all
check yaml...............................................................Passed
check for added large files..............................................Passed
check for case conflicts.................................................Passed
check json...........................................(no files to check)Skipped
check for merge conflicts................................................Passed
check for broken symlinks................................................Passed
detect destroyed symlinks................................................Passed
detect private key.......................................................Passed
terraform-docs...........................................................Passed
Terraform fmt............................................................Passed
```
```bash
$ export PCT_TFPATH="${PWD}/path/w ith/space/terraform"; pre-commit run --all
check yaml...............................................................Passed
check for added large files..............................................Passed
check for case conflicts.................................................Passed
check json...........................................(no files to check)Skipped
check for merge conflicts................................................Passed
check for broken symlinks................................................Passed
detect destroyed symlinks................................................Passed
detect private key.......................................................Passed
terraform-docs...........................................................Passed
Terraform fmt............................................................Failed
- hook id: terraform_fmt
- exit code: 127

/home/user1/.cache/pre-commit/repo2_2krz94/hooks/terraform_fmt.sh: line 52: /home/user1/work/applications/it_infra_tf_ccoe_app_bstrp_test/path/w: No such file or directory
/home/user1/.cache/pre-commit/repo2_2krz94/hooks/terraform_fmt.sh: line 52: /home/user1/work/applications/it_infra_tf_ccoe_app_bstrp_test/path/w: No such file or directory
/home/user1/.cache/pre-commit/repo2_2krz94/hooks/terraform_fmt.sh: line 52: /home/user1/work/applications/it_infra_tf_ccoe_app_bstrp_test/path/w: No such file or directory
/home/user1/.cache/pre-commit/repo2_2krz94/hooks/terraform_fmt.sh: line 52: /home/user1/work/applications/it_infra_tf_ccoe_app_bstrp_test/path/w: No such file or directory
/home/user1/.cache/pre-commit/repo2_2krz94/hooks/terraform_fmt.sh: line 52: /home/user1/work/applications/it_infra_tf_ccoe_app_bstrp_test/path/w: No such file or directory
/home/user1/.cache/pre-commit/repo2_2krz94/hooks/terraform_fmt.sh: line 52: /home/user1/work/applications/it_infra_tf_ccoe_app_bstrp_test/path/w: No such file or directory
/home/user1/.cache/pre-commit/repo2_2krz94/hooks/terraform_fmt.sh: line 52: /home/user1/work/applications/it_infra_tf_ccoe_app_bstrp_test/path/w: No such file or directory
/home/user1/.cache/pre-commit/repo2_2krz94/hooks/terraform_fmt.sh: line 52: /home/user1/work/applications/it_infra_tf_ccoe_app_bstrp_test/path/w: No such file or directory

Terraform validate.......................................................Failed
- hook id: terraform_validate
- exit code: 127

'terraform init' failed, '/home/user1/work/applications/it_infra_tf_ccoe_app_bstrp_test/path/w ith/space/terraform validate' skipped: .
/home/user1/.cache/pre-commit/repo2_2krz94/hooks/_common.sh: line 539: /home/user1/work/applications/it_infra_tf_ccoe_app_bstrp_test/path/w: No such file or directory


Validation failed: terraform
/home/user1/.cache/pre-commit/repo2_2krz94/hooks/terraform_validate.sh: line 135: /home/user1/work/applications/it_infra_tf_ccoe_app_bstrp_test/path/w: No such file or directory


```

</details>

### Environment information

* OS:  

Bug is present on both Windows and Linux (initially discovered on Windows due to "Program Files" in path).

* `uname -a` and/or `systeminfo | Select-String "^OS"` output:

```bash
Linux iac-dev-box-user1 6.5.0-1025-azure #26~22.04.1-Ubuntu SMP Thu Jul 11 22:33:04 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

* Tools availability and versions:

```bash
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
pre-commit 3.6.0
OpenTofu v1.8.0
Terraform v1.9.3
python SKIPPED
Python 3.10.12
checkov 3.2.140
infracost SKIPPED
terraform-docs SKIPPED
terragrunt SKIPPED
terrascan SKIPPED
TFLint version 0.52.0
+ ruleset.terraform (0.8.0-bundled)
tfsec SKIPPED
trivy SKIPPED
tfupdate SKIPPED
hcledit SKIPPED
```

* `.pre-commit-config.yaml`:

<details><summary>file content</summary>

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      # - id: trailing-whitespace
      # - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: destroyed-symlinks
      # - id: detect-aws-credentials
      - id: detect-private-key
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.18.0"
    hooks:
      - id: terraform-docs-go
        args: ["markdown", "--output-file", "../README.md", "terraform"]
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.94.1"
    hooks:
      - id: terraform_fmt
        args: ["terraform"]
      - id: terraform_validate
        args: ["terraform"]
```

</details>

### PR DESCRIPTION
**Pull request by robinbowes**
Put an `x` into the box if that apply:

- [ ] This PR introduces breaking change.
- [x] This PR fixes a bug.
- [ ] This PR adds new functionality.
- [ ] This PR enhances existing functionality.

### Description of your changes

Add quotes around variable containing path to terraform so ti works when the path contains a space.

Fixes #713

### CODE REVIEW

**Comment by yermulnik** [comment]
@robinbowes Thanks for the contribution. It looks like we'd better quote all instances of `$tf_path`. Would you be up to update your PR accordingly? See https://github.com/antonbabenko/pre-commit-terraform/issues/713#issuecomment-2332555888 just in case to avoid race condition =)

```shell
> sift -n '[^"]\$tf_path'
hooks/terraform_validate.sh:121:  $tf_path validate "${args[@]}" &> /dev/null && {
hooks/terraform_validate.sh:135:    validate_output=$($tf_path validate "${args[@]}" 2>&1)
hooks/terraform_validate.sh:139:    validate_output=$($tf_path validate -json "${args[@]}" 2>&1)
hooks/terraform_validate.sh:162:      validate_output=$($tf_path validate "${args[@]}" 2>&1)
hooks/terraform_providers_lock.sh:158:  $tf_path providers lock "${args[@]}"
hooks/_common.sh:539:      init_output=$($tf_path init -backend=false "${TF_INIT_ARGS[@]}" 2>&1)
hooks/_common.sh:545:        init_output=$($tf_path init -backend=false "${TF_INIT_ARGS[@]}" 2>&1)
hooks/terraform_fmt.sh:52:  $tf_path fmt "${args[@]}"
```

**Comment by robinbowes** [comment]
> @robinbowes Thanks for the contribution. It looks like we'd better quote all instances of `$tf_path`. Would you be up to update your PR accordingly? See [#713 (comment)](https://github.com/antonbabenko/pre-commit-terraform/issues/713#issuecomment-2332555888) just in case to avoid race condition =)
> 
> ```shell
> > sift -n '[^"]\$tf_path'
> hooks/terraform_validate.sh:121:  $tf_path validate "${args[@]}" &> /dev/null && {
> hooks/terraform_validate.sh:135:    validate_output=$($tf_path validate "${args[@]}" 2>&1)
> hooks/terraform_validate.sh:139:    validate_output=$($tf_path validate -json "${args[@]}" 2>&1)
> hooks/terraform_validate.sh:162:      validate_output=$($tf_path validate "${args[@]}" 2>&1)
> hooks/terraform_providers_lock.sh:158:  $tf_path providers lock "${args[@]}"
> hooks/_common.sh:539:      init_output=$($tf_path init -backend=false "${TF_INIT_ARGS[@]}" 2>&1)
> hooks/_common.sh:545:        init_output=$($tf_path init -backend=false "${TF_INIT_ARGS[@]}" 2>&1)
> hooks/terraform_fmt.sh:52:  $tf_path fmt "${args[@]}"
> ```

Heh, I fixed all the occurrences you listed before I saw your comment.

I made one additional change in terraform_providers_lock.sh to use $tf_path instead of the text "terraform" to match the style used in other files.

Should be good to go now.

**Review by MaxymVlasov — APPROVED** [review]

**Comment by antonbabenko** [comment]
This PR is included in version 1.94.2 :tada:

**Comment by pcarn** [comment]
This caused a breaking change, FYI.

My CI job calls `pre-commit run --all-files`, and it started failing with 1.94.2.

I found that terraform was not installed on the CI environment. Before 1.94.2, the pre-commit job would pass anyway. Now it fails for terraform being missing.

It did expose that terraform wasn't actually installed, so it was helpful in that way. But I wanted to call out the breaking change.

**Comment by MaxymVlasov** [comment]
1. I don't see how changes in this PR could affect your CI
2. Improving checks which prevents unexpected behavior (from your description, previously it just bypassed checks) is `fix` by definition, not breaking change.
3. Also, it should be checked here - https://github.com/antonbabenko/pre-commit-terraform/blob/89f45610a846f56273a6c4290b3c42534175949e/hooks/_common.sh#L450-L500

     @pcarn Please open an issue if you can provide minimum reproduction example via GH workflows etc, as I not sure how it was even possible to out for function above without error, if there is no binary, and you didn't specify path in configuration explicitly

**Comment by pcarn** [comment]
To be clear, I’m glad this change was made. When terraform was not installed, it was not actually doing any checks or doing any formatting. It succeeded silently. 

I’m mentioning it because when it started failing with no changes of my own, I looked at the changelog and nothing looked related. I went version by version to find that it was this that changed it.

minimal steps to reproduce:

* set up a repo with terraform files that are unformatted. 
* do not have terraform installed. 
* use this hook
* 

Before this commit, it would pass, and make no formatting changes. 

After this commit, it fails, and says terraform is not installed. (Which is probably the better behavior)

**Comment by MaxymVlasov** [comment]
Okay, it's actually asked for `terraform` binary before < 1.90.0. 
But somehow check start bypass in 1.90.0 (https://github.com/antonbabenko/pre-commit-terraform/pull/670)
And this regression fixed in some magical way in 1.94.2

I'll add this to release notes

And we need tests here -_-

**Pull request merged**
