### PR TITLE
fix: Pass args and env vars to terraform validate

### LINKED ISSUE #116: Pass custom tfvar file to terraform validate
I'd like `terraform validate` to run with a `-var-file=test/terraform.tfvars` parameter.

Is there an easy way to pass this as an option to the `terraform_validate.sh` script?

### PR DESCRIPTION
**Pull request by robinbowes**
Adds support for passing env vars and arguments to terraform_validate

Requires #124.

Fixes #116 and #119 , obsoletes #114 + #118.

### CODE REVIEW

**Comment by robinbowes** [comment]
@paullschock + @antonbabenko  - please review

**Comment by robinbowes** [comment]
Any love for this, @antonbabenko ?

What do you think, @paullschock ?

**Comment by antonbabenko** [comment]
Hi Robin,

Thanks for your work!

I am on vacation till the middle of August, and I will certainly go through this and many more PRs once I am back.

Best regards,
Anton.

**Comment by paullschock** [comment]
@robinbowes sorry for the delay in looking this over, I'll test this out to be sure, but from a visual examination I think I prefer your implementation and will pull my PR in favor of this.

**Comment by robinbowes** [comment]
@antonbabenko Any chance you might review this and approve/reject it? I'm really needing the functionality to be able to test modules using `terraform validate`.

Thanks.

**Comment by antonbabenko** [comment]
@robinbowes Thanks for your work on this project (not just on this PR)! I highly appreciate your contributions which I can't always review promptly enough.

PS: I am reviewing this now.

**Comment by antonbabenko** [comment]
This is a big one. In the future, please split this into several smaller which would make review process easier for me: one PR which just moves `lib_getopt` outside, and another (one or more) which adds new features.

I ran some examples with some of my projects and terraform-aws-modules and it seems to work as expected.

Could you please make a PR where lib_getopt is used instead of inline code in `terraform_docs` and `terraform_tfsec`? I promise I will review them much faster.

**Comment by antonbabenko** [comment]
[v1.33.0](https://github.com/antonbabenko/pre-commit-terraform/releases/v1.33.0) has been just released.

**Comment by robinbowes** [comment]
> This is a big one. In the future, please split this into several smaller which would make review process easier for me: one PR which just moves `lib_getopt` outside, and another (one or more) which adds new features.

I did actually do that here: https://github.com/antonbabenko/pre-commit-terraform/pull/124  

> I ran some examples with some of my projects and terraform-aws-modules and it seems to work as expected.
> 
> Could you please make a PR where lib_getopt is used instead of inline code in `terraform_docs` and `terraform_tfsec`? I promise I will review them much faster.

Will do.

**Comment by paullschock** [comment]
Thank you @antonbabenko  and @robinbowes, you guys rock, this solves a big issue for me!!

**Pull request merged**
