### PR TITLE
fix(`terraform_validate`): Run `terraform init` on "Missing required provider" error

### LINKED ISSUE #585: terraform_validate hook doesn't run `terraform init` if a provider is not installed even when using `--retry-once-with-cleanup=true`
### Describe the bug

In a situation where the Terraform providers are not installed the `terraform_validate` hook doesn't execute `terraform init` to install the providers even if the hook is configured with the option `--retry-once-with-cleanup=true`. I ran in a situation where the `terraform_validate` hook terminated with an error showing the following error output (from Terraform apparently):

```
Validation failed: my-project
{
  "format_version": "1.0",
  "valid": false,
  "error_count": 6,
  "warning_count": 0,
  "diagnostics": [
    {
      "severity": "error",
      "summary": "Missing required provider",
      "detail": "This configuration requires provider registry.terraform.io/hashicorp/external, but that provider isn't available. You may be able to install it automatically by running:
  terraform init"
    },
    {
      "severity": "error",
      "summary": "Missing required provider",
      "detail": "This configuration requires provider registry.terraform.io/hashicorp/google, but that provider isn't available. You may be able to install it automatically by running:
  terraform init"
    },
    {
      "severity": "error",
      "summary": "Missing required provider",
      "detail": "This configuration requires provider registry.terraform.io/hashicorp/null, but that provider isn't available. You may be able to install it automatically by running:
  terraform init"
    },
    {
      "severity": "error",
      "summary": "Missing required provider",
      "detail": "This configuration requires provider registry.terraform.io/hashicorp/random, but that provider isn't available. You may be able to install it automatically by running:
  terraform init"
    },
    {
      "severity": "error",
      "summary": "Missing required provider",
      "detail": "This configuration requires provider registry.terraform.io/hashicorp/tls, but that provider isn't available. You may be able to install it automatically by running:
  terraform init"
    },
    {
      "severity": "error",
      "summary": "Missing required provider",
      "detail": "This configuration requires provider registry.terraform.io/techbeck03/guacamole, but that provider isn't available. You may be able to install it automatically by running:
  terraform init"
    }
  ]
}
```

The problem is that the function `match_validate_errors` in the `terraform_validate.sh` script doesn't have the error `Missing required provider` in its list of errors for which `terraform init` should be called to fix them. 

### How can we reproduce it?

Use it with a fresh TF config where no provider has been installed, yet.

### PR DESCRIPTION
**Pull request by fwolfheimer**
Put an `x` into the box if that apply:

- [ ] This PR introduces breaking change.
- [x] This PR fixes a bug.
- [ ] This PR adds new functionality.
- [ ] This PR enhances existing functionality.

### Description of your changes

Fixes #585

### CODE REVIEW

**Review by yermulnik — APPROVED** [review]

**Comment by MaxymVlasov** [comment]
>How can we reproduce it?

Use it with a fresh TF config where no provider has been installed, yet.

>How can we test changes

<Nothing>


Can you please provide a tf configuration that failed? I don't get what is " fresh TF config where no provider has been installed"

**Comment by fwolfheimer** [comment]
@MaxymVlasov , this happened for a fairly complex project setup that contains multiple separate Terraform configurations each with multiple modules. I was not able to create a really minimal example which reproduces the behavior I have seen for the real project. However, as the error message I saw (in the linked bug report) is an error from Terraform which can be fixed by running `terraform init` and this error message is not part of the list of "well known errors" in `terraform_validate.sh` which causes an error in the hook execution which can be easily fixed by adding this error message to the list, I'd argue that trying to find a way  to create a minimal reproducer of the actual situation is not of high value here. Hope you agree.

**Review by MaxymVlasov — APPROVED** [review]
In one day there will be an introduced tests, but for now, it's kinda acceptable

**Comment by antonbabenko** [comment]
This PR is included in version 1.83.6 :tada:

**Comment by MaxymVlasov** [comment]
In any case, thanks for contibution

**Pull request merged**
