### PR TITLE
feat: Removed `coreutils` (realpath) from dependencies for MacOS

### LINKED ISSUE #336: Realpath error with 1.63.0
The latest version of pre-commit terraform throws an error due to lack of realpath command. Are there any new packages that need to be locally installed for pre-commit terraform to run successfully?

```
Terraform validate.......................................................Failed
- hook id: terraform_validate
- exit code: 1

/Users/.../.cache/pre-commit/repoln3cyzan/hooks/terraform_validate.sh: line 9: realpath: command not found
/Users/.../.cache/pre-commit/repoln3cyzan/hooks/terraform_validate.sh: line 11: ./_common.sh: No such file or directory
```

### PR DESCRIPTION
**Pull request by MaxymVlasov**
Put an `x` into the box if that apply:

- [ ] This PR introduces breaking change.
- [ ] This PR fixes a bug.
- [ ] This PR adds new functionality.
- [x] This PR enhances existing functionality.

### Description of your changes

Fixes #336, #349 and #367

### How can we test changes

Run any hook on MacOs w/o `coreutils`

```yaml
repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: 307f48dae422203f31fa888f6cad7d12014ad260
  hooks:
```

### CODE REVIEW

**Review by antonbabenko — APPROVED** [review]
Why did we have a previous solution in the first place? Why there are so many alternative solutions listed here - https://stackoverflow.com/questions/3572030/bash-script-absolute-path-with-os-x ? :)

**Comment by yermulnik** [comment]
> Why there are so many alternative solutions listed here

Coz those who use MacOS are sentenced by Apple to use old, outdated, and EOL'ed NIXish software where Apple doesn't want to conform with licensing in favour of their users suffering from incompetence to install additional modern software using simple solutions like `Homebrew` and use right tools for the right tasks 🤷🏻
So since there are plenty of such people using `pre-commit-terraform` I feel like Max is right in replacing the "right tool" with a workaround, which looks most reliable among dozens of alternatives.

**Review by yermulnik — APPROVED** [review]
Let's make happy those people who miss a lot of useful tools.
Linux:
```
> dpkg -L coreutils | fgrep /bin/ | awk -F/ '{print $NF}' | sort | uniq | wc -l
104
```
Homebrew on MacOS:
```
> brew list --verbose coreutils | fgrep /bin/ | awk -F/ '{print $NF}' | sort | uniq | wc -l
133
```

**Comment by MaxymVlasov** [comment]
>Why did we have a previous solution in the first place?

Because it run out of the box in Linux and `realpath` was introduced in `terraform_validate` by [mcdonnnj](https://github.com/antonbabenko/pre-commit-terraform/commits?author=mcdonnnj) on 4 Apr 2020 (v1.29.0) in https://github.com/antonbabenko/pre-commit-terraform/commit/7694fb9b9a2187670f55233d0317c05f6b0080d5


I recheck repo for `realpath` - now it not exist

**Review by yermulnik — APPROVED** [review]

**Review by antonbabenko — APPROVED** [review]

**Comment by antonbabenko** [comment]
This PR is included in version 1.68.0 :tada:

**Pull request merged**
