### PR TITLE
feat: Skip legacy modules (with provider block) in terraform_wrapper_module_for_each hook

### PR DESCRIPTION
**Pull request by ajax-ryzhyi-r**
Put an `x` into the box if that apply:

- [ ] This PR introduces breaking change.
- [x] This PR fixes a bug.
- [ ] This PR adds new functionality.
- [ ] This PR enhances existing functionality.

### Description of your changes

Modules that have `provider` blocks do not support `for_each`, `count`, or `depends_on` meta arguments. Therefore, there is no need to generate wrappers for these modules because they cannot be called.

This PR adds a skip for modules that contain a `provider` block.

### How can we test changes

Run the `terraform_wrapper_module_for_each` against the module with the `provider` block - wrapper should not be created.

### CODE REVIEW

**Comment by antonbabenko** [comment]
Thank you for your contribution. Could you please provide a small code snippet of the module with a `provider` block which should not be generated by the hook? And/or link to the related issue in Terraform?

**Comment by ajax-ryzhyi-r** [comment]
> Thank you for your contribution. Could you please provide a small code snippet of the module with a `provider` block which should not be generated by the hook? And/or link to the related issue in Terraform?

This is not actually an issue; it is expected behavior. Modules with local provider definitions are considered legacy modules by HashiCorp and do not support the `for_each` meta argument. However, in rare cases, there may be a need to add some provider configurations in the module. In such cases, successfully generated wrappers could be confusing because they cannot be used.

Terraform docs: https://developer.hashicorp.com/terraform/language/modules/develop/providers#legacy-shared-modules-with-provider-configurations

**Review by antonbabenko — APPROVED** [review]

**Comment by antonbabenko** [comment]
Thank you for the explanation! Merging...

**Comment by antonbabenko** [comment]
This PR is included in version 1.83.0 :tada:

**Pull request merged**
