### PR TITLE
docs: Updated docs for infracost_breakdown to match Infracost 0.10

### PR DESCRIPTION
**Pull request by antonbabenko**
Infracost 0.10 has some changes in the names of the flags.

Ref: https://twitter.com/AliKhajeh/status/1530081914865868802

### CODE REVIEW

**Review by yermulnik — APPROVED** [review]
Is this backward compatible with `infracost` versions prior to `v0.10`?

**Comment by yermulnik** [comment]
> I don't think so. Infracost 0.10 has been released 3 days ago.

Maybe revert this change then and add it back as a supplemental note for Infracost 0.10 specifically? 🤔

**Comment by antonbabenko** [comment]
I don't think it is necessary because we always expect (and recommend) users to update their tools if something seems off. This change is mentioning one of an argument but there are several more that users may be using (depending on the version of the tool they have installed).

**Comment by antonbabenko** [comment]
This PR is included in version 1.72.2 :tada:

**Pull request merged**
