### PR TITLE
fix: analyse all folders with tflint and don't stop on first execution

### PR DESCRIPTION
**Pull request by bmbferreira**
Put an `x` into the box if that apply:

- [ ] This PR introduces breaking change.
- [x] This PR fixes a bug.
- [ ] This PR adds new functionality.
- [ ] This PR enhances existing functionality.

### Description of your changes

In a monorepo tflint is currently stopping after analysing the first module. This is because of the `set -e` that causes the script to exit. This change disables it temporarily for executing `tflint`, catches the exit codes from the `tflint` executions and then uses the exit code for the function. It also removes the `pushd`/`popd` since it is not necessary because tflint can just receive the path as an argument.

### How has this code been tested

Create a mono repo with two or more modules in different folders, with code that makes tflint report something. Notice that before this change, it just analyses one of the modules. With this change it will keep analysing the modules and report the output for all of them.

### CODE REVIEW

**Review by MaxymVlasov — APPROVED** [review]
Checked, it works fine.
LGTM

**Comment by antonbabenko** [comment]
@bmbferreira Please fix the failing CI.

**Review by yermulnik — APPROVED** [review]
LGTM too 👍🏻

**Comment by yermulnik** [comment]
@antonbabenko 
> @bmbferreira Please fix the failing CI.

The error doesn't seem to be related to this PR: https://github.com/antonbabenko/pre-commit-terraform/runs/4461845751?check_suite_focus=true#step:8:77

**Comment by antonbabenko** [comment]
@yermulnik Magic "пендаль" fixed the build.

**Comment by yermulnik** [comment]
Hahaha, great example of mastering a kick up the arse mate 👍🏻

**Comment by bmbferreira** [comment]
Thank you for merging the PR 🙇‍♂️ 
Really happy that I was able to do a small contribution for this useful repo! 😄  Thank you for your work 🙌

**Comment by maxbrunet** [comment]
> It also removes the `pushd`/`popd` since it is not necessary because tflint can just receive the path as an argument.

This is needed, some `tflint` flags like `--module` needs the workspace directory to be initialized. And like `terraform`, `tflint` picks up the `.terraform` directory from the current working directory

**Pull request merged**
