### PR TITLE
feat: Improved speed of `pre-commit run -a` for multiple hooks

### LINKED ISSUE #309: Improve perfomance during `pre-commit --all` (`-a`) run
Some hooks recursively check all files in provided dir.

So performance degradation exists only in the `pre-commit run --all` situation, because it will provide all existing repo files to hook:

https://github.com/antonbabenko/pre-commit-terraform/blob/e6ffbcd3def77c7caa471d008daefa13f9095127/terrascan.sh#L15-L19

Then, unique paths are found and run `terrascan` for each repo folder:

https://github.com/antonbabenko/pre-commit-terraform/blob/e6ffbcd3def77c7caa471d008daefa13f9095127/terrascan.sh#L29-L30

It works literally how it should work: checks only diffs.

So, good to know when the `--all` (`-a`) argument passed to `pre-commit` and just run `terrascan -d GIT_REPO_ROOT`, not all-all dirs.

---

## Useful info

* [How to run hook performance test](https://github.com/antonbabenko/pre-commit-terraform/blob/master/.github/CONTRIBUTING.md#run-hook-performance-test)
* `pre-commit` automatically parallel checks to exiting cores, so you need to run tests on a repo that has at least 2x more tf-dirs than CPU cores you have. If you have not so big repo - just copy-paste code-structure a few times, and you'll get needed.

* Create solution as function, that can be called from `terrascan_()` hook function and depends on the result, in `if` run other flow and stop execution with `exit 0`

---

- [ ] `checkov` run checks recursively. need `-d GIT_REPO_POOT_PATH`

- [ ] `tfsec` runs recursively without any additional args.

- [ ] `terragrunt_fmt`  ( [`terragrunt hclfmt`](https://github.com/gruntwork-io/terragrunt/blob/33b07484c81dd3302c579c28d6a03f915ce3eac2/docs/_docs/04_reference/cli-options.md#hclfmt)) runs recursively without any additional args.

- [ ] `terrascan` runs recursively without any additional args.

- [x] `terragrunt_validate` have option [`terragrunt run-all validate`](https://github.com/gruntwork-io/terragrunt/blob/33b07484c81dd3302c579c28d6a03f915ce3eac2/docs/_docs/04_reference/cli-options.md#validate-all-deprecated-use-run-all) that run checks recursively.   #327

---

Founded in https://github.com/antonbabenko/pre-commit-terraform/pull/305

### PR DESCRIPTION
**Pull request by MaxymVlasov**
…m_tfsec`, `terragrunt_fmt` and `terragrunt_validate`

Put an `x` into the box if that apply:

- [ ] This PR introduces breaking change.
- [ ] This PR fixes a bug.
- [ ] This PR adds new functionality.
- [x] This PR enhances existing functionality.

### Description of your changes

Speedup hooks execution on `pre-commit run --all`

Closes #309

### How can we test changes

```yaml
repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: 7ebbe57df62dce6d50cfe11a12566850d96a9613
  hooks:
    - id: terraform_tfsec
      #args:
      #  - >
      #    --args=--config-file=.tfsec.json
    - id: terragrunt_fmt
    - id: terragrunt_validate
```

### CODE REVIEW

**Comment by antonbabenko** [comment]
This PR is included in version 1.64.0 :tada:

**Comment by sergei-ivanov** [comment]
I am afraid that this may likely produce incorrect results with `tfsec`, see https://github.com/aquasecurity/tfsec/issues/1452

**Comment by MaxymVlasov** [comment]
I didn't think that is bug. As I see (https://github.com/aquasecurity/tfsec/issues/1452#issuecomment-1026957993), this is expected `tfsec` behavior.:

>... input variables are taken into account when loading a module from a parent vs loading it directly by scanning it's directory, just like if you ran terraform in the root vs the module dir you would see a slightly different plan depending on input vars.



Anyway, if you'll see come incorrect results, feel free to submit issue/PR

**Comment by sergei-ivanov** [comment]
From tfsec maintainers' point of view, it is expected behaviour. And I can see their point, that's why I did not challenge it there.

But from the end user's point of view, tfsec produces different results if I run it from the top of the repository. It flags up a lot of false positives that are not flagged up if I run it module-by-module.

That's why I am concerned that the pre-commit hook is going to produce different results if I run it for all files vs. changed files only. Previously it was consistent in that respect.

**Pull request merged**
