### PR TITLE
fix: Fixed regression with exit code in `terraform_docs` hook

### LINKED ISSUE #413: terraform_docs fails when using release v.1.7.4
### Describe the bug

When running the `tf_docs` hook with release v1.7.4, the hook fails with:

```
Terraform docs...........................................................Failed
- hook id: terraform_docs
- exit code: 1
```

### How can we reproduce it?

Run the `tf_docs` hook with v1.7.3 and witness success.
Run the `tf_docs` hook with v1.7.4 and witness failure.

### Environment information

* OS: macOS 12.4

* Tools availability and versions:

```bash
pre-commit 2.20.0
Terraform v1.2.4
python SKIPPED
Python 3.9.13
checkov checkov SKIPPED
terraform-docs version v0.16.0 darwin/amd64
terragrunt SKIPPED
terrascan version: v1.15.2
TFLint version 0.38.1
tfsec v1.26.3
```

* `.pre-commit-config.yaml`:

<details><summary>file content</summary>

```yaml
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.73.0
    hooks:
      - id: tfupdate
      - id: terraform_docs
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_providers_lock
```

</details>

### PR DESCRIPTION
**Pull request by MaxymVlasov**
Put an `x` into the box if that apply:

- [ ] This PR introduces breaking change.
- [x] This PR fixes a bug.
- [ ] This PR adds new functionality.
- [ ] This PR enhances existing functionality.

### Description of your changes
Fixes #413

`[ -e "" ]` produces result code 1 if the file is not found. And that implicitly return as result, which is not expected

### How can we test changes

```yaml
repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: 168b3aee5c9927ab104667173eb2555d381c8402
  hooks:
    - id: terraform_docs
```

### CODE REVIEW

**Comment by yermulnik** [comment]
@MaxymVlasov 
> `[ -e "" ]` produces exit code 1 if the file is not found. And that implicitly return as result, which is not expected

I'm not able to reproduce this:
```
set -eo pipefail

echo $BASH_VERSION

[ -e "somefile_which_does_not_exit" ] && echo Ok

echo "End"
```
Execution output:
```
3.2.0(5)-beta
End
```

**Review by opp-svega — APPROVED** [review]

**Comment by MaxymVlasov** [comment]
```bash
$ [ -e $somefile_which_does_not_exit ] && echo Ok
$ $?
1: command not found
```

@yermulnik

**Comment by MaxymVlasov** [comment]
You're right, it is named not "exit code", but something like "command execution result code", but that's no matter if `[ -e "" ]` is the last construction in function

**Comment by antonbabenko** [comment]
This PR is included in version 1.74.1 :tada:

**Comment by robinbowes** [comment]
Good fix, btw. (no need to test for existence when using `rm -f`)

**Comment by yermulnik** [comment]
@robinbowes Yep, I was about to suggest adding 1) explicit `return` or 2) ` || true` or 3) "proper" `if/then/fi` to that function to properly handle the `[ -e` test condition failure, though... `rm -f ...` can handle this on its own despite an extraneous call to `rm` where we could avoid doing this.
And, yep, it was me who asked to add `[ -e` test condition to the code previously 😺

**Pull request merged**
