### PR TITLE
fix: terraform_docs compatible with Git bash on Windows

### PR DESCRIPTION
**Pull request by matiaszilli**
Adds support for terraform_docs running on Git Bash over Windows environment.

It fixs #128

### CODE REVIEW

**Comment by fbuinosquy** [comment]
Please merge.

**Comment by matiaszilli** [comment]
Please @antonbabenko can you merge it?. Thanks.

**Comment by antonbabenko** [comment]
Good one! Thanks for the nudge, too :)

[v1.42.0](https://github.com/antonbabenko/pre-commit-terraform/releases/v1.42.0) has been just released.

**Comment by robinbowes** [comment]
Is `awk` available in git bash on Windows?

If so, this will do the trick:
```
terraform version | awk 'NR > 1 { exit } ; /0.12/ { ++count } ; END { printf "%d\n", count }'
```
This awk program consists of three elements:

- `NR > 1 { exit }` - exit after the first line
- `/0.12/ { ++count }` - if the line matches the pattern, increment the `count` variable
- `END { printf "%d\n", count }` - when we exit (either at the end of the file, or if "exit" is called), print the value of `count` as a number

**Pull request merged**
