### PR TITLE
Output filepath (#161)

### PR DESCRIPTION
**Pull request by varac**

### CODE REVIEW

**Comment by varac** [comment]
This is an example of the output changed by this PR:

```
❯ pre-commit run --all-files                          
Check for merge conflicts................................................Passed
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Check Yaml...............................................................Passed
Check for added large files..............................................Passed
Terraform fmt............................................................Passed
Terraform validate.......................................................Passed
Terraform docs...........................................................Passed
Terraform validate with tfsec............................................Passed
Checkov..................................................................Passed
Terraform validate with tflint...........................................Failed
- hook id: terraform_tflint
- exit code: 3

Running tflint in cluster/default
Running tflint in environments/cloud/dev
Running tflint in environments/cloud/varac
1 issue(s) found:

Warning: Module should include an empty outputs.tf file (terraform_standard_module_structure)

  on outputs.tf line 1:
   (source code not available)

Reference: https://github.com/terraform-linters/tflint/blob/v0.21.0/docs/rules/terraform_standard_module_structure.md

Running tflint in cluster/default
Running tflint in modules/infrastructure/cce
Running tflint in modules/infrastructure/ssh
Running tflint in modules/infrastructure/vpc
Running tflint in cluster/default
Running tflint in environments/cloud/varac
1 issue(s) found:

Warning: Module should include an empty outputs.tf file (terraform_standard_module_structure)

  on outputs.tf line 1:
   (source code not available)

Reference: https://github.com/terraform-linters/tflint/blob/v0.21.0/docs/rules/terraform_standard_module_structure.md

Running tflint in environments/cloud/dev
Running tflint in modules/infrastructure/ssh
Running tflint in modules/infrastructure/vpc
```

**Comment by varac** [comment]
In the above output you see that tflint runs multiple times in the same directory, is this expected ?

**Comment by 1oglop1** [comment]
> In the above output you see that tflint runs multiple times in the same directory, is this expected ?

@varac Hi, really like this feature.

Maybe if you included `tree` or repo you tried it on would help.

**Comment by varac** [comment]
> Maybe if you included tree or repo you tried it on would help. 

It's a private repo so I don't like to disclose it publicly. I think you are referring to the fact that that tflint runs multiple times in the same directory ? I'll better open a dedicated issue for this. This PR is just for printing the path tflint is working on.

**Comment by 1oglop1** [comment]
> > Maybe if you included tree or repo you tried it on would help.
> 
> It's a private repo so I don't like to disclose it publicly. I think you are referring to the fact that that tflint runs multiple times in the same directory ? I'll better open a dedicated issue for this. This PR is just for printing the path tflint is working on.

In that case I think that makes sense.
Also creating some dummy repository to prove it would be helpful imo

**Comment by varac** [comment]
@antonbabenko ping, what do you think about this PR ?

**Comment by 1oglop1** [comment]
@Vlaaaaaaad I noticed you liked my PR, and since @antonbabenko takes preference on issues/PRs from sponsors it may help if you participate in the discussion to give @antonbabenko incentive to look at this 1 line change

**Comment by kpankonen** [comment]
> In the above output you see that tflint runs multiple times in the same directory, is this expected ?

if multiple files in a single directory are changed (or `pre-commit run --all-files` is run), it's possible that files from one directory will end up split across pre-commit processes.  that will cause this hook to run multiple times in a single directory

pre-commit provides the [require_serial](https://pre-commit.com/#hooks-require_serial) option which helps but is also slower

**Review by MaxymVlasov — COMMENTED** [review]
Thank you for your contribution!

When test PR, I found that dirs will print always, not only when TFLint found errors.

Found working solution, but no chance to integrate it to this PR, so I open #234 that do it.

**Pull request closed without merging**
