### PR TITLE
chore: Use lib_getopt for all hooks and some style tweaks

### PR DESCRIPTION
**Pull request by robinbowes**
This change updates `terraform_docs` and `terraform_tfsec` to use `lib_getopt` instead of including the `getopt()` function as inline code.

I've also tweaked `terraform_validate` to set more local variables, and set bash strict mode for all these three scripts (`set -euo pipefail`).

@antonbabenko Please test and confirm the functionality has not changed.

### CODE REVIEW

**Comment by antonbabenko** [comment]
There is something wrong when I run sample code with `terraform_docs`, `terraform_validate`, `terraform_tfsec` hooks.

Example:
```
$ pre-commit try-repo -a ~/Sites/pre-commit-terraform terraform_docs
===============================================================================
Using config:
===============================================================================
repos:
-   repo: ../../pre-commit-terraform
    rev: 8447a4b0deb03463b79c3efb741589c3c1506d08
    hooks:
    -   id: terraform_docs
===============================================================================
[INFO] Initializing environment for ../../pre-commit-terraform.
Terraform docs...........................................................Failed
- hook id: terraform_docs
- exit code: 2

/var/folders/vy/wm1qhfns0rl564mb6w5w1b3c0000gn/T/tmphnsd74km/repo68xsrh9i/lib_getopt: line 415: space: unbound variable
Try `getopt --help' for more information.
```

**Comment by robinbowes** [comment]
Ah, that will be the `set -u` - let me work on that.

**Comment by robinbowes** [comment]
@antonbabenko How does this look?

**Comment by antonbabenko** [comment]
Great! Thanks a lot for this, too.

[v1.34.0](https://github.com/antonbabenko/pre-commit-terraform/releases/v1.34.0) has been just released.

**Comment by bmonkman** [comment]
FYI, this seems to have broken docs parsing for me in a project with multiple sub-modules (Running on MacOS)
Using the version before this, if I parse docs it properly generates docs for all my sub-modules. When I use the version that includes this change it only generates docs for a single module.

**Pull request merged**
